### ISSUE TITLE
API Secret Input Field

### ISSUE THREAD

**Issue by bokamm** [HanSolo/Gluco-Status#1]
Hallo!
Fantastic app!
Would it be possible to include an API Secret field with the server URL? Currently, the app only asks for the server link.
However, when I set the variable AUTH_DEFAULT_ROLES=denied in order to block unauthorized access to the nightscout site, Gluco-Status no longer reads data from the server. I found no way to include the secret in the URL, so I was wondering if this functionality can be added to the app. For example, XDrip asks for both, link and secret.
Thank you!

**Comment by HanSolo** [comment]
Hi there, sure I will check and add it. Doesn’t it have the Nightscout token field?

**Comment by HanSolo** [comment]
Oh and btw there is another version of it named GlucoStatusFX which you can find here 
 https://github.com/HanSolo/glucostatusfx which has more features like day comparison. You will find the installabe files here:
https://github.com/HanSolo/glucostatusfx/releases

**Comment by bokamm** [comment]
Thank you for the prompt reply!
There is no token field. And thank you for sharing also GlucoStatusFX! This one has a token field — but it does not run in the menu tray, which is the fantastic aspect of this Gluco Status...

**Comment by HanSolo** [comment]
Where do you run GlucoStatusFX on? I run it on mac and linux and both are in the system tray.

**Comment by bokamm** [comment]
MacOS 13.5 (22G74), M1 Max. I installed the GlucoStatusFX-17.0.37.pkg.

**Comment by HanSolo** [comment]
Hmm…I see it in the system tray, same as GlucoStatus. Nevertheless, will also add the Token field to GlucoStatus and investigate the FX system tray problem.

**Comment by bokamm** [comment]
Thank you!

**Comment by bokamm** [comment]
My bad: FX is in the system tray but the text is white, so I did not see it on my light desktop background. GlucoStatus has the text in black. I switched between light and dark mode, but no effect on the FX colour.

**Comment by HanSolo** [comment]
Ah…ok…easy to fix, will release both versions later today…need breakfast first 😁👍🏻

**Comment by bokamm** [comment]
Sure thing! Thank you and enjoy breakfast!

**Comment by HanSolo** [comment]
Both apps are updated, because I don't use an api secret, I did not test it yet, so can you check if it works for you? The GlucoStatusFX version now also supports switching between dark and bright mode in the settings.

**Comment by HanSolo** [comment]
Setup an api-secret and tested it but it looks like it does not work yet in GlucoStatus but it does work in GlucoStatusFX...will further check.

**Comment by HanSolo** [comment]
Fixed the problem in GlucoStatus, so please wait until version 5.8 will appear in the app store.

**Comment by HanSolo** [comment]
Now it's also working correctly in GlucoStatusFX version 17.0.41

**Comment by bokamm** [comment]
Thank you so much! I tried today all morning, but neither app connects once I set AUTH_DEFAULT_ROLES=denied. I created an access token (for readable) and it works with other apps (e.g. Xdrip). I also tried the admin access key and they still do not connect. What role should I pick for the access token?
cf.: https://nightscout.github.io/nightscout/security/

**Comment by HanSolo** [comment]
Hmm…ok, let me figure that out. Will keep you up to date on this issue.

**Comment by bokamm** [comment]
Thank you!

**Comment by HanSolo** [comment]
Just to make sure we are on the same info, you set the nightscout token in the app to your API_SECRET and the nightscout url for example like this https://yoursitename.yourplatform.com/?token=YOUR_CUSTOM_TOKEN

I could also change the nightscout token field to api secret and add another field for token to make it easier if that would help?

**Comment by bokamm** [comment]
I have tried:

a)
Nightscout URL: https://yoursitename.yourplatform.com
Nightscout Token: CUSTOM_TOKEN

(CUSTOM_TOKEN: set up a "subject" in the Nightscout Admin Panel, gave it the role "readable" and received a token).

b)
Nightscout URL: https://yoursitename.yourplatform.com
Nightscout Token: ACCESS_KEY

(ACCESS_KEY: The key used to gain admin access)

And the following combinations:
Nightscout URL: https://yoursitename.yourplatform.com/?token=CUSTOM_TOKEN
Nightscout Token: CUSTOM_TOKEN

Nightscout URL: https://yoursitename.yourplatform.com/?token=ACCESS_KEY
Nightscout Token: ACCESS_KEY

And the following combinations:
Nightscout URL: https://yoursitename.yourplatform.com/?token=CUSTOM_TOKEN
Nightscout Token: [empty]

Nightscout URL: https://yoursitename.yourplatform.com/?token=ACCESS_KEY
Nightscout Token: [empty]

Nothing of the above worked unfortunately.

**Comment by HanSolo** [comment]
Check…found the problem, will modify it in the way that there will be two fields, api secret and token. This should work, expect a new version later today and thanks for reporting 👍🏻😁

**Comment by bokamm** [comment]
Wow, great, thank you!

**Comment by HanSolo** [comment]
There is already a new version of GlucoStatusFX (17.0.45)  which contains the API_SECRET and the TOKEN field in the settings dialog. You might want to try that first because the GlucoStatus app takes longer to adjust and push through the Apple app store.

**Comment by bokamm** [comment]
Thank you again for the time to adjust this but the moment I switch to "denied" the app no longer connects (neither with API SECRET nor with a token). Other apps do connect.
I am using Northflank and have quite the weird URL.
Could this be a reason?

**Comment by HanSolo** [comment]
Interesting...would you mind sending me your url, the api-secret and some token to check it locally? Would make things way easier. You can send it to me via mail han.solo@mac.com
Or if you have maybe another way of sending it, it would also be fine.

**Comment by HanSolo** [comment]
GlucoStatusFX 17.0.47 is out and this one works with your URL, API_SECRET and TOKEN. Be aware, that the initial loading process takes a bit longer because it loads all data from the last 90 days. From that on it should only append the last value.

**Comment by bokamm** [comment]
Fantastic! Yes, now it works! thank you so much!
Can I buy you a coffee somehow or donate?

**Comment by HanSolo** [comment]
No worries, I'm glad it works. If you have ideas on how to improve it, please let me know 😁

**Comment by bokamm** [comment]
Sure, will do! Thank you again so much!

**Comment by HanSolo** [comment]
Just for your info, there is a new version of GlucoStatusFX over at [github](https://github.com/HanSolo/glucostatusfx/releases) and there will also be another update of GlucoStatus in the app store today. Both updates mainly contain minor fixes and UI tweaks to improve readability :)

**Comment by bokamm** [comment]
OK, great! Will check them out!

**Comment by bokamm** [comment]
Both are working and looking great! I think I will stay with the appstore version, though, because it means one less app in my too-full Dock. Thank you again for solving the token input!

**Comment by HanSolo** [comment]
My pleasure 😁. Oh and btw just in case you also use an iPhone with an Apple Watch, there is my mobile version called Gluco-Tracker 😜

**Comment by bokamm** [comment]
I did not know but I also have no Apple Watch (yet!). Will check it out still!
